<a href="https://colab.research.google.com/github/mufeed0786/AI_CSV_Dashboard/blob/main/Live_API_Data_Integration_Real_Time_Dashboard_with_python_and_Power_BI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd

!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)

In [5]:
import requests

In [6]:
#importiing the countries
url = " https://api.worldbank.org/countries?format=json&per_page=300"
response = requests.get(url)
response.status_code

200

In [7]:
data = response.json()
print(data[0])
print(len(data))

{'page': 1, 'pages': 1, 'per_page': '300', 'total': 295}
2

In [8]:
countries = data[1]
countries = pd.DataFrame(countries)
countries.head()

,id,iso2Code,name,region,adminregion,incomeLevel,lendingType,capitalCity,longitude,latitude
0,ABW,AW,Aruba,"{'id': 'LCN', 'iso2code': 'ZJ', 'value': 'Lati...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'HIC', 'iso2code': 'XD', 'value': 'High...","{'id': 'LNX', 'iso2code': 'XX', 'value': 'Not ...",Oranjestad,-70.0167,12.5167
1,AFE,ZH,Africa Eastern and Southern,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
2,AFG,AF,Afghanistan,"{'id': 'MEA', 'iso2code': 'ZQ', 'value': 'Midd...","{'id': 'MNA', 'iso2code': 'XQ', 'value': 'Midd...","{'id': 'LIC', 'iso2code': 'XM', 'value': 'Low ...","{'id': 'IDX', 'iso2code': 'XI', 'value': 'IDA'}",Kabul,69.1761,34.5228
3,AFR,A9,Africa,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,
4,AFW,ZI,Africa Western and Central,"{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': ''}","{'id': 'NA', 'iso2code': 'NA', 'value': 'Aggre...","{'id': '', 'iso2code': '', 'value': 'Aggregates'}",,,

In [9]:
countries["region"] = countries["region"].apply(lambda x:x["value"])

In [10]:
countries["incomeLevel"] = countries["incomeLevel"].apply(lambda x:x["value"])

In [11]:
countries["lendingType"] = countries["lendingType"].apply(lambda x:x["value"])

In [12]:
countries.drop(columns=["adminregion"], inplace = True)

In [13]:
countries.drop(columns=["capitalCity"], inplace = True)

In [14]:
countries.tail()

,id,iso2Code,name,region,incomeLevel,lendingType,longitude,latitude
290,XZN,A5,Sub-Saharan Africa excluding South Africa and ...,Aggregates,Aggregates,Aggregates,,
291,YEM,YE,"Yemen, Rep.","Middle East, North Africa, Afghanistan & Pakistan",Low income,IDA,44.2075,15.352
292,ZAF,ZA,South Africa,Sub-Saharan Africa,Upper middle income,IBRD,28.1871,-25.746
293,ZMB,ZM,Zambia,Sub-Saharan Africa,Lower middle income,IDA,28.2937,-15.3982
294,ZWE,ZW,Zimbabwe,Sub-Saharan Africa,Lower middle income,Blend,31.0672,-17.8312

In [15]:
countries["region"].unique()

array(['Latin America & Caribbean ', 'Aggregates',
       'Middle East, North Africa, Afghanistan & Pakistan',
       'Sub-Saharan Africa ', 'Europe & Central Asia',
       'East Asia & Pacific', 'South Asia', 'North America'], dtype=object)

In [17]:
#code for indicators
base_url = "https://api.worldbank.org/v2/indicators?format=json"
response = requests.get(base_url)
response.status_code

200

In [21]:
indicators_data = response.json()

In [23]:
indicators_data[0]

{'page': 1, 'pages': 591, 'per_page': '50', 'total': 29544}